language: node_js
node_js:
- lts/*
install:
- yarn
script:
- yarn test
cache: yarn
deploy:
  provider: npm
  email: oupenguin@gmail.com
  api_key: "$NPM_TOKEN"
  on:
    branch: master
  skip-cleanup: true